#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: my-laptop
    username: lucky
    password: "$6$rounds=4096$KbDwTjgs7Ec6v2Rf$Q/j1FxN9.MD5cF.XE9J.pI8aKh2B8EswW0RgUcnWk5WzgMMQBy4cJbmvAK5ZzBc2w1RiRbrn6zQU3LgPoPPZV/"
  locale: en_US.UTF-8
  timezone: America/Chicago
  keyboard:
    layout: us
    variant: ''
  storage:
    layout:
      name: encrypted-lvm
  packages:
    - git
    - curl
    - vim
    - htop
    - nala
    - neofetch
    - gnome-weather
    - extension-manager
    - ufw
    - gufw
    - libayatana-appindicator3-1
    - gir1.2-ayatanaappindicator3-0.1
    - gnome-shell-extension-appindicator
    - python3
    - python3-pip
    - python3-venv
    - ipython
    - build-essential
    - python3-dev
    - fonts-cantarell
    - fonts-firacode
    - virtualbox
  snaps:
    - name: brave
    - name: skype
    - name: signal-desktop
    - name: proton-pass
    - name: spotify
    - name: telegram-desktop
    - name: discord
    - name: steam
    - name: transmission
    - name: whatsie
    - name: obs-studio
    - name: mpv
    - name: code  # VS Code Snap
    - name: qemu-ut-pdk
  late-commands:
    - apt-get update && apt-get install -y gnome-weather extension-manager protonmail-desktop
    - echo "Downloading and installing ProtonVPN"
    - wget -O /tmp/protonvpn-stable-release.deb https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.6_all.deb
    - sudo dpkg -i /tmp/protonvpn-stable-release.deb && sudo apt update
    - apt-get install -y protonvpn protonvpn-gnome-desktop
    - rm /tmp/protonvpn-stable-release.deb
    - echo "Installing Hack Nerd Font"
    - mkdir -p ~/.local/share/fonts
    - wget -qO- https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip -O /tmp/Hack.zip
    - unzip -o /tmp/Hack.zip -d ~/.local/share/fonts
    - fc-cache -fv
    - gnome-extensions install blur-my-shell@aunetx
    - gnome-extensions install caffeine@patapon.info
    - gnome-extensions install vuemeter@trogonproject
    - gnome-extensions install weather-or-not@kylorlovett
    - gnome-extensions enable blur-my-shell@aunetx
    - gnome-extensions enable caffeine@patapon.info
    - gnome-extensions enable vuemeter@trogonproject
    - gnome-extensions enable weather-or-not@kylorlovett
    - gsettings set org.gnome.desktop.interface font-name 'Cantarell Regular 11'
    - gsettings set org.gnome.desktop.interface document-font-name 'Cantarell Regular 11'
    - gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Code Medium 11'
    - xdg-settings set default-web-browser brave-browser.desktop
    - xdg-mime default mpv.desktop audio/*
    - xdg-mime default mpv.desktop video/*
    - xdg-mime default eog.desktop image/*
    - gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
    - gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    - ufw enable
    - echo "Setup Complete" > /etc/motd
